/**
 * @module
 *
 * The package index: the curated public surface of `@aztlan/guarantees`.
 *
 * Every value a consumer imports from the package root is admitted here by
 * name. Importing this module has no side effects.
 */
export {
  CEILINGS,
  CONTRACT_VERSION,
  computeBudget,
  computeP95,
  type Engine,
  EXIT_CODES,
  type ExitCode,
  type Expect,
  type ImageRef,
  ISOLATIONS,
  type Isolation,
  judgeRun,
  judgeWall,
  KINDS,
  type Kind,
  labelSchema,
  type Measurement,
  markerSchema,
  type Phase,
  type Pipeline,
  type Plan,
  POOLED_KINDS,
  type Probe,
  parseRegister,
  planTier,
  probeEngine,
  probeSchema,
  RESERVED_IDS,
  type Reading,
  Refusal,
  type Register,
  type RegisterFault,
  RegisterRefusal,
  type Row,
  type RunBudget,
  readProbe,
  readReport,
  reapStale,
  registerSchema,
  reportSchema,
  resolveImage,
  rewriteRunBudget,
  type Spawn,
  type Spawned,
  type SpawnOptions,
  type Stamp,
  type Summary,
  TIERS,
  type Tier,
  toExitCode,
  UNMEASURED_S,
  type Verdict,
} from "./lib/index.js";
