/**
 * @module
 *
 * The package index: the curated public surface of `@aztlan/guarantees`.
 *
 * Every value a consumer imports from the package root is admitted here by
 * name. Nothing here has a side effect of its own; the load is not free,
 * because every entry re-exports from the one lib barrel and that barrel
 * mints the selftest bodies, which import the runner.
 */
export {
  type Accepted,
  acceptGolden,
  CEILINGS,
  CONTRACT_VERSION,
  computeBudget,
  computeP95,
  type Engine,
  EXIT_CODES,
  type ExitCode,
  type Expect,
  type ImageRef,
  ISOLATIONS,
  type Isolation,
  judgeRun,
  judgeWall,
  KINDS,
  type Kind,
  labelSchema,
  type Measurement,
  markerSchema,
  type Phase,
  type Pipeline,
  type Plan,
  POOLED_KINDS,
  type Probe,
  type ProveContext,
  parseRegister,
  planTier,
  probeEngine,
  probeSchema,
  proveTier,
  type Ran,
  RESERVED_IDS,
  type Reading,
  Refusal,
  type Register,
  type RegisterFault,
  RegisterRefusal,
  type Row,
  type RunBudget,
  type RunContext,
  readProbe,
  readReport,
  reapStale,
  registerSchema,
  reportSchema,
  resolveImage,
  rewriteRunBudget,
  runEntry,
  type Spawn,
  type Spawned,
  type SpawnOptions,
  type Stamp,
  type Summary,
  TIERS,
  type Tier,
  toExitCode,
  UNMEASURED_S,
  type Verdict,
} from "./lib/index.js";
